### ISSUE TITLE
How i can check phone registered?

### ISSUE THREAD

**Issue by TheSimpleCoder** [nimix3/tgsharp#3]
Hello. How i can check phone registered?
For example. isPhoneRegistered("+15859564565") return true: false

https://core.telegram.org/method/auth.checkPhone

**Comment by nimix3** [comment]
Hello,

simply by using:
`tgsharp.checkPhone(Number);`

after creating an instance of TelegramApi, use the method above to check the registered phones.
Note: that telegram will temporarily block your IP if you check too many phones with single IP address!

**Comment by TheSimpleCoder** [comment]
![image](https://user-images.githubusercontent.com/29470610/46569395-094d4300-c95d-11e8-94b0-e2bf1d308051.png)
checkPhone always return "isMember".
What i do wrong?

**Comment by nimix3** [comment]
I check and found that telegram remove the ability to check numbers without active session! that's because it returns wrong.
