### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by mehdiyahyavi** [nimix3/tgsharp#4]
Hi guy
I'm Trying to Test login that is it working or not.
using this line of code:

`string result = api.login("+9891xxxx265", true, false, true);`

it's work, and send a verfication code to typed number in code. repeat two time, and work, but at three time and over, this in not working and result=Err.Null
have an any idea?

**Comment by nimix3** [comment]
Hi,

Telegram will ban your IP address or number from getting the code if you attempt too many!
You don't need to do so, you should register number first then session store as a file and in next time just load number.

See the example project attached...

Good Luck
