### ISSUE TITLE
Solution _api66 not build

### ISSUE THREAD

**Issue by Maverick1983** [nimix3/tgsharp#5]
Hi, I have error on build

> tgsharp\library\source\org\telegram\mtproto\log\LogInterface.cs' could not be found

> tgsharp\library\source\org\telegram\mtproto\log\Logger.cs' could not be found.

Dependeces not find

![image](https://user-images.githubusercontent.com/20558694/53635149-81721900-3c1c-11e9-8106-99c2759fbd6c.png)

**Comment by nimix3** [comment]
Hello,

You can download IKVM c# library from [https://sourceforge.net/projects/ikvm/files](https://sourceforge.net/projects/ikvm/files/) easily also there are exist in this repository, just download and Add the reference to your project.

Good luck
